### PR TITLE
finished directory, on page I

### PR DESCRIPTION
**Pull request by dennisrcao**

### CODE REVIEW

**Review by jakemgilfix — APPROVED** [review]

**Review by ChrisPadovan — CHANGES_REQUESTED** [review]
I'm seeing a good amount of comments and leftover console.log statements, would prefer to have these removed before merging into main.

**Review by jakemgilfix — CHANGES_REQUESTED** [review]
console.log()s and renaming my component

**Review by edgar-carrillo — CHANGES_REQUESTED** [review]
**Nitpicks**

1. I'm seeing the file `pages/Page-D-SwipeGroup.js` here is just a div. Does this need to be here? If there's no use for it removing would be nice to prevent code bloat.

2. I'm seeing commented out code that should not be here unless needed at the very bottom of file `Page-E-matchGroup.js `

I'm also seeing that the file `pages/restaurant.js` has been renamed to `pages/Page-J-Restaurant.js` Which is fine since it's now following a convention that seems to be what we are all following. 

I like the reformating of src/index.js. a bit confused on some of the spacing choices though.

Way less console.logs though and I'm loving it!

Would just like to see 1. & 2. addressed before approving this

**Review by edgar-carrillo — COMMENTED** [review]
**Nitpicks**

I saw you left a comment about page-d regarding `pages/Page-D-SwipeGroup.js` without making a change to it in a commit, I'd recommend keeping commits related only to the files changed and comments within the PR.

1. My vote for page-d would be to still remove it and only for the person working on said file to add the file within a commit and to not add placeholder files.

Otherwise, I see the comment removed and nothing major that needs to changed! I'm going to stay neutral to also see how others feel about this if you want to keep it in (page-d). My vote for approving will skew with how others approve the stuff!

@jakemgilfix @ChrisPadovan 

(P.S. Don't take my reviews personally, I'm pretty brutal lol)

**Comment by dennisrcao** [comment]
> **Nitpicks**
> 
> I saw you left a comment about page-d regarding `pages/Page-D-SwipeGroup.js` without making a change to it in a commit, I'd recommend keeping commits related only to the files changed and comments within the PR.
> 
> 1. My vote for page-d would be to still remove it and only for the person working on said file to add the file within a commit and to not add placeholder files.
> 
> Otherwise, I see the comment removed and nothing major that needs to changed! I'm going to stay neutral to also see how others feel about this if you want to keep it in (page-d). My vote for approving will skew with how others approve the stuff!
> 
> @jakemgilfix @ChrisPadovan
> 
> (P.S. Don't take my reviews personally, I'm pretty brutal lol)

Okay that's fine, Ill remove it through Github, also note that on the Directory Page it says Page-D [ Needs to be done] as a reminder.

**Review by jakemgilfix — APPROVED** [review]

**Pull request merged**
