### PR TITLE
Selected restaurants

### PR DESCRIPTION
**Pull request by ChrisPadovan**
Added styling and zero merge conflicts.

### CODE REVIEW

**Review by jakemgilfix — APPROVED** [review]

**Review by dennisrcao — APPROVED** [review]
Approved

**Comment by ec-rilo** [comment]
reviewing now

**Review by edgar-carrillo — CHANGES_REQUESTED** [review]
**Nitpicks**
1. Looks like a console.log on line 55

2. I'm also seeing commented out code on line 40 - 45. Does this still need to be here?

The dummy data's fine with me!

No need to close this branch, I'd just create a commit that addresses these changes and push that commit up to this branch. Then I'll do another review! 

P.S. When I pulled your branch it doesn't look like you have the most recent changes, doesn't affect this branch though just a random comment :)

**Review by edgar-carrillo — APPROVED** [review]
F🔥I🔥R🔥E

**Pull request merged**
